# ============================================================================
# DIAGNOSTIC TOOL: BATCH PLOT TRAVERSAL AUDIT
# ============================================================================
library(tidyverse)
library(fs)

# ============================================================================
#### 1. USER CONFIGURATION ####
# ============================================================================
# Point this at the "Wide" output file generated by your main pipeline
WIDE_DATA_CSV <- "C:/Users/james.baker/Forest Research/TW CBC-TBA-NextGenBritishConifers - Share/Sitka/High GCA Fullsib P85-P87 experiments/Arecleoch 12/Arecleoch_12_Full_Data_With_Flags.csv"

PLOT_SIZE      <- 49       # Options: 8 (for 8x1 arrays) or 49 (for 7x7 grids), 25 (5x5)

# The Trusted Baseline (Typically whichever growth metric that has sensible correlations)
BASELINE_TRAIT <- "Dm_15"  

# List ALL traits you suspect might have traversal errors. 
# You can list one, or ten! e.g., c("Ht_03", "Pil_17", "Fr_05")  
# NB: Traits that correlate well with each other but poorly with other growth traits are extremely suspect! 
TEST_TRAITS    <- c("Ht_03", "Ht_06") 

#
#### TEMPORAL CHAINING TOGGLE: 
#### Set to TRUE to run the diagnostic on the '_Corrected.csv' file instead of the raw data
#
USE_CORRECTED_DATA <- TRUE
#
####
####
#

# --- Auto-Path Logic & Subdirectory Management (Do not edit) ---
if(USE_CORRECTED_DATA) {
  WIDE_DATA_CSV <- stringr::str_replace(RAW_WIDE_DATA_CSV, "(?i)\\.csv$", "_Corrected.csv")
  out_suffix <- "_Chained"
} else {
  WIDE_DATA_CSV <- RAW_WIDE_DATA_CSV
  out_suffix <- ""
}

OUTPUT_DIR <- dirname(WIDE_DATA_CSV)
DIAG_DIR   <- file.path(OUTPUT_DIR, "Traversal_Diagnostics")

# Create the diagnostics subdirectory if it doesn't exist
if(!dir.exists(DIAG_DIR)) dir.create(DIAG_DIR)

# Backup the Master Helper if we are doing a chained run
helper_path <- file.path(OUTPUT_DIR, "TRAVERSAL_HELPER_MASTER.csv")
if (USE_CORRECTED_DATA && file.exists(helper_path)) {
  backup_name <- paste0("TRAVERSAL_HELPER_MASTER_PreChainBackup_", format(Sys.time(), "%Y%m%d_%H%M%S"), ".csv")
  file.copy(helper_path, file.path(DIAG_DIR, backup_name))
  message(paste("Backed up original Master Helper to:", backup_name))
}

# ============================================================================
#### 2. VIRTUAL ASSESSOR MATH ENGINE ####
# ============================================================================
get_grid_layout <- function(plot_size, interior_only = FALSE) {
  if (plot_size == 8) return(matrix(1:8, nrow=1))
  n <- as.integer(sqrt(plot_size))
  mat <- matrix(1:(n*n), nrow=n, byrow=TRUE)
  if(interior_only && n >= 3) mat <- mat[2:(n-1), 2:(n-1)]
  return(mat)
}

get_traversal_path <- function(layout_mat, start_corner="top_left", direction="horizontal", snake=FALSE) {
  if (length(layout_mat) == 8) {
    if (start_corner %in% c("reversed", "bottom_right")) return(rev(as.vector(layout_mat)))
    return(as.vector(layout_mat))
  }
  n_rows <- nrow(layout_mat)
  n_cols <- ncol(layout_mat)
  row_indices <- if (start_corner %in% c("bottom_left", "bottom_right")) rev(seq_len(n_rows)) else seq_len(n_rows)
  col_indices <- if (start_corner %in% c("top_right", "bottom_right")) rev(seq_len(n_cols)) else seq_len(n_cols)
  
  path <- c()
  if (direction == "horizontal") {
    for (i_idx in seq_along(row_indices)) {
      i <- row_indices[i_idx]
      cols <- col_indices
      if (snake && i_idx %% 2 == 0) cols <- rev(cols)
      for (j in cols) path <- c(path, layout_mat[i, j])
    }
  } else {
    for (j_idx in seq_along(col_indices)) {
      j <- col_indices[j_idx]
      rows <- row_indices
      if (snake && j_idx %% 2 == 0) rows <- rev(rows)
      for (i in rows) path <- c(path, layout_mat[i, j])
    }
  }
  return(path)
}

# ============================================================================
#### 3. BATCH PROCESSING LOOP ####
# ============================================================================
message(paste("Loading master data from:", basename(WIDE_DATA_CSV)))
df_raw <- read_csv(WIDE_DATA_CSV, show_col_types = FALSE)

# Loop through every trait provided in TEST_TRAITS
for (TEST_TRAIT in TEST_TRAITS) {
  
  cat("\n======================================================================\n")
  cat(">>> INITIATING DIAGNOSTIC FOR TRAIT:", TEST_TRAIT, "<<<\n")
  cat("======================================================================\n")
  
  # --- 3a. Auto-Detect Baseline Survival ---
  base_age <- suppressWarnings(as.numeric(str_extract(BASELINE_TRAIT, "\\d+")))
  
  # 1. Guess the exact matching survival trait based on the zero-padded age
  target_surv_base <- paste0("Sur_", str_pad(base_age, 2, pad = "0"))
  
  # 2. Check if it exists. If not, find the closest one chronologically.
  if (target_surv_base %in% names(wide_data)) {
    BASELINE_SURV <- target_surv_base
  } else {
    surv_cols <- grep("(?i)^Sur_", names(wide_data), value = TRUE)
    if (length(surv_cols) > 0) {
      surv_ages <- suppressWarnings(as.numeric(str_extract(surv_cols, "\\d+")))
      closest_idx <- which.min(abs(surv_ages - base_age))
      BASELINE_SURV <- surv_cols[closest_idx]
      message(paste("  -> Exact survival not found. Auto-detected closest BASELINE_SURV:", BASELINE_SURV))
    } else {
      stop("CRITICAL ERROR: No survival traits found in dataset. Zombie filter cannot run.")
    }
  }
  
  # --- Data Loading & Zero Filtering ---
  working_data <- df_raw %>%
    select(Plot, Tree, 
           Base_Val = !!sym(BASELINE_TRAIT), Base_Surv = !!sym(BASELINE_SURV), 
           Test_Val = !!sym(TEST_TRAIT), Test_Surv = !!sym(TEST_SURV)) %>%
    filter(!str_detect(Plot, "(?i)Filler")) %>%
    mutate(
      Tree = as.numeric(Tree),
      Plot = as.character(Plot),
      # REPEATABLE ZERO FILTER: Treat '0' in measurement as NA (erroneous data)
      Base_Val = na_if(as.numeric(Base_Val), 0),
      Test_Val = na_if(as.numeric(Test_Val), 0)
    )
  
  # --- Auto-detect Interior ---
  test_trees_used <- unique(working_data %>% filter(!is.na(Test_Val)) %>% pull(Tree))
  layout_interior <- as.vector(get_grid_layout(PLOT_SIZE, interior_only = TRUE))
  
  is_test_interior <- FALSE
  if (PLOT_SIZE > 8 && length(test_trees_used) > 0 && all(test_trees_used %in% layout_interior)) {
    is_test_interior <- TRUE
    message(paste("Detected", TEST_TRAIT, "as an INTERIOR-ONLY measurement."))
  }
  
  layout_mat <- get_grid_layout(PLOT_SIZE, interior_only = is_test_interior)
  canonical_path <- get_traversal_path(layout_mat, "top_left", "horizontal", FALSE)
  
  base_age <- suppressWarnings(as.numeric(str_extract(BASELINE_TRAIT, "\\d+")))
  test_age <- suppressWarnings(as.numeric(str_extract(TEST_TRAIT, "\\d+")))
  
  # --- Permutation Generator ---
  if (PLOT_SIZE == 8) {
    combos <- tibble(Perm_ID = 1:2, start_corner = c("normal", "reversed"), direction = "horizontal", snake = FALSE)
  } else {
    combos <- expand_grid(start_corner = c("top_left", "bottom_left", "top_right", "bottom_right"), direction = c("horizontal", "vertical"), snake = c(FALSE, TRUE)) %>% mutate(Perm_ID = row_number())
  }
  
  plots <- unique(working_data$Plot)
  results_list <- list()
  
  message(paste("Testing", length(plots), "plots against", nrow(combos), "traversal permutations..."))
  
  for (p in plots) {
    plot_data <- working_data %>% filter(Plot == p)
    if(sum(!is.na(plot_data$Base_Val)) < 3 || sum(!is.na(plot_data$Test_Val)) < 3) next
    
    for (i in 1:nrow(combos)) {
      sc <- combos$start_corner[i]
      dir <- combos$direction[i]
      snk <- combos$snake[i]
      
      tested_path <- get_traversal_path(layout_mat, sc, dir, snk)
      translation_df <- tibble(Original_Tree = canonical_path, Mapped_Tree = tested_path)
      
      mapped_test <- plot_data %>% select(Tree, Test_Val, Test_Surv) %>% inner_join(translation_df, by = c("Tree" = "Original_Tree"))
      joined <- plot_data %>% select(Tree, Base_Val, Base_Surv) %>% left_join(mapped_test, by = c("Tree" = "Mapped_Tree"))
      
      mapped_test <- plot_data %>% select(Tree, Test_Val, Test_Surv) %>% inner_join(translation_df, by = c("Tree" = "Original_Tree"))
      joined <- plot_data %>% select(Tree, Base_Val, Base_Surv) %>% left_join(mapped_test, by = c("Tree" = "Mapped_Tree"))
      
      # --- NEW SMART ZOMBIE FILTER ---
      if (!is.na(base_age) && !is.na(test_age) && base_age > test_age) {
        # Anchor is OLDER. A Zombie is Dead at Test (Young), but Alive at Base (Old)
        zombie_count <- sum(joined$Test_Surv == 0 & (!is.na(joined$Base_Val) | joined$Base_Surv == 1), na.rm = TRUE)
      } else {
        # Anchor is YOUNGER. A Zombie is Dead at Base (Young), but Alive at Test (Old)
        zombie_count <- sum(joined$Base_Surv == 0 & (!is.na(joined$Test_Val) | joined$Test_Surv == 1), na.rm = TRUE)
      }
      
      is_valid <- (zombie_count == 0)
      
      cor_data <- joined %>% filter(!is.na(Base_Val) & !is.na(Test_Val))
      spearman_cor <- if(nrow(cor_data) >= 3) cor(cor_data$Base_Val, cor_data$Test_Val, method = "spearman") else NA_real_
      
      results_list[[length(results_list) + 1]] <- tibble(Plot = p, Perm_ID = combos$Perm_ID[i], start_corner = sc, direction = dir, snake = snk, Zombies_Created = zombie_count, Is_Biologically_Valid = is_valid, Sample_Size = nrow(cor_data), Spearman_Cor = spearman_cor)
    }
  }
  all_results <- bind_rows(results_list)
  
  # --- Synthesis & Recommendations ---
  message("Synthesizing recommendations...")
  recommendations <- all_results %>%
    group_by(Plot) %>%
    mutate(
      Normal_Cor = Spearman_Cor[start_corner %in% c("top_left", "normal") & direction == "horizontal" & snake == FALSE],
      Normal_Valid = Is_Biologically_Valid[start_corner %in% c("top_left", "normal") & direction == "horizontal" & snake == FALSE]
    ) %>%
    filter(Is_Biologically_Valid == TRUE) %>%
    arrange(desc(Spearman_Cor)) %>%
    slice(1) %>%
    ungroup() %>%
    mutate(
      Action_Required = case_when(
        start_corner %in% c("top_left", "normal") & direction == "horizontal" & snake == FALSE ~ "None (Normal is Best)",
        Normal_Valid == FALSE ~ "CRITICAL FIX: Normal layout creates Zombies",
        (Spearman_Cor - Normal_Cor) > 0.15 ~ "SUGGESTED FIX: Massive correlation improvement",
        TRUE ~ "Review Manually (Marginal Improvement)"
      )
    ) %>%
    select(Plot, Action_Required, Best_Start = start_corner, Best_Dir = direction, Best_Snake = snake, Best_Cor = Spearman_Cor, Normal_Cor, Sample_Size) %>%
    arrange(desc(Action_Required))
  
  write_csv(all_results, file.path(DIAG_DIR, paste0(BASELINE_TRAIT, "_vs_", TEST_TRAIT, out_suffix, "_All_Permutations.csv")))
  write_csv(recommendations, file.path(DIAG_DIR, paste0("Suggested_Fixes_", TEST_TRAIT, "_anchored_to_", BASELINE_TRAIT, out_suffix, ".csv")))
  
  # --- Visualization ---
  message("Generating visualization panels...")
  before_df <- working_data %>% select(Plot, Tree, Base_Val, Test_Val) %>% mutate(State = "1. Original Raw Data")
  after_list <- list()
  
  for (p in unique(working_data$Plot)) {
    p_data <- working_data %>% filter(Plot == p)
    rec <- recommendations %>% filter(Plot == p)
    if (nrow(rec) == 1 && !str_detect(rec$Action_Required, "(?i)None")) {
      tested_path <- get_traversal_path(layout_mat, rec$Best_Start, rec$Best_Dir, rec$Best_Snake)
      translation_df <- tibble(Original_Tree = canonical_path, Mapped_Tree = tested_path)
      fixed_test <- p_data %>% select(Tree, Test_Val) %>% inner_join(translation_df, by = c("Tree" = "Original_Tree"))
      p_joined <- p_data %>% select(Plot, Tree, Base_Val) %>% left_join(fixed_test, by = c("Tree" = "Mapped_Tree"))
      after_list[[length(after_list) + 1]] <- p_joined
    } else {
      after_list[[length(after_list) + 1]] <- p_data %>% select(Plot, Tree, Base_Val, Test_Val)
    }
  }
  after_df <- bind_rows(after_list) %>% mutate(State = "2. Targeted Fixes")
  
  global_sc <- if(PLOT_SIZE == 8) "reversed" else "bottom_right"
  global_path <- get_traversal_path(layout_mat, global_sc, "horizontal", FALSE)
  global_translation <- tibble(Original_Tree = canonical_path, Mapped_Tree = global_path)
  global_test <- working_data %>% select(Plot, Tree, Test_Val) %>% inner_join(global_translation, by = c("Tree" = "Original_Tree"))
  global_df <- working_data %>% select(Plot, Tree, Base_Val) %>% left_join(global_test, by = c("Plot", "Tree" = "Mapped_Tree")) %>% mutate(State = "3. Global Rule Fix")
  
  plot_df <- bind_rows(before_df, after_df, global_df) %>% filter(!is.na(Base_Val) & !is.na(Test_Val))
  
  calc_cor <- function(df) round(cor(df$Base_Val, df$Test_Val, use = "pairwise.complete.obs", method = "spearman"), 3)
  cor_before <- calc_cor(before_df); cor_after <- calc_cor(after_df); cor_global <- calc_cor(global_df)
  
  p_compare <- ggplot(plot_df, aes(x = Base_Val, y = Test_Val)) +
    geom_point(alpha = 0.5, size=0.25, color = "#2c3e50") +
    geom_smooth(method = "lm", color = "#e74c3c", linetype = "dashed", se = FALSE) +
    facet_wrap(~State, ncol = 3) + theme_bw() +
    labs(
      title = paste("Plot Traversal Correction:", BASELINE_TRAIT, "vs", TEST_TRAIT),
      subtitle = sprintf("Trial Correlations  ->  Raw: %s  |  Targeted Fix: %s  |  Global Fix: %s", cor_before, cor_after, cor_global),
      x = paste("Trusted Baseline:", BASELINE_TRAIT), y = paste("Suspected Trait:", TEST_TRAIT)
    ) +
    theme(strip.background = element_rect(fill = "#ecf0f1"), strip.text = element_text(face = "bold", size = 11), plot.title = element_text(face = "bold", size = 14))
  
  ggsave(file.path(DIAG_DIR, paste0(BASELINE_TRAIT, "_vs_", TEST_TRAIT, out_suffix, "_Correction_Plot.jpg")), plot = p_final, width = 16, height = 6, dpi = 300)
  
  # --- Forensic Report ---
  target_desc <- "TOP-LEFT start, HORIZONTAL rows, TYPEWRITER (no snake)"
  dominant_fix <- recommendations %>% filter(str_detect(Action_Required, "FIX")) %>% count(Best_Start, Best_Dir, Best_Snake) %>% arrange(desc(n)) %>% slice(1)
  
  cat("\nFORENSIC TRAVERSAL AUDIT: ", TEST_TRAIT, " relative to ", BASELINE_TRAIT, "\n")
  cat("1. TARGET ORIENTATION: ->", target_desc, "\n")
  
  if (nrow(dominant_fix) > 0) {
    cat("2. DETECTED FIELD BEHAVIOR (The 'Incorrect' Pattern)\n")
    cat(sprintf("   -> %s corner, walking %s (Snake: %s)\n", toupper(dominant_fix$Best_Start), toupper(dominant_fix$Best_Dir), dominant_fix$Best_Snake))
    
    rebels <- recommendations %>% filter(str_detect(Action_Required, "FIX")) %>% filter(Best_Start != dominant_fix$Best_Start | Best_Dir != dominant_fix$Best_Dir | Best_Snake != dominant_fix$Best_Snake)
    if (nrow(rebels) > 0) {
      cat("3. PATTERN DEVIATIONS (Rebel Plots)\n")
      for(r in 1:nrow(rebels)) cat(sprintf("   - Plot %-4s: Assessor used %s, %s (Snake: %s)\n", rebels$Plot[r], toupper(rebels$Best_Start[r]), toupper(rebels$Best_Dir[r]), rebels$Best_Snake[r]))
    }
  } else {
    cat("2. AUDIT RESULT: No significant traversal errors detected.\n")
  }
  
  # --- Master Helper Export (DEFENSIVE) ---
  main_pipe_helper <- recommendations %>%
    filter(str_detect(Action_Required, "FIX")) %>%
    mutate(
      Trial_ID = basename(OUTPUT_DIR),
      Trait_ID = TEST_TRAIT, 
      Anchor_Used = BASELINE_TRAIT,
      Manual_Verification = "Pending",
      Best_Snake = as.character(Best_Snake), # Ensure logic doesn't crash bind_rows
      Plot = as.character(Plot)
    ) %>%
    select(Trial_ID, Trait_ID, Anchor_Used, Plot, Best_Start, Best_Dir, Best_Snake, Best_Cor, Normal_Cor)
  
  helper_path <- file.path(OUTPUT_DIR, "TRAVERSAL_HELPER_MASTER.csv")
  
  if (file.exists(helper_path)) {
    # Read everything as character to prevent type clashes
    existing_helper <- read_csv(helper_path, col_types = cols(.default = "c")) 
    combined_helper <- existing_helper %>% 
      filter(Trait_ID != TEST_TRAIT) %>% 
      bind_rows(main_pipe_helper %>% mutate(across(everything(), as.character)))
  } else {
    combined_helper <- main_pipe_helper
  }
  
  write_csv(combined_helper, helper_path)
  message(paste("Master Integration Helper updated at:", helper_path, "\n"))
}
cat(">>> BATCH DIAGNOSTIC COMPLETE <<<\n")

