# ============================================================================
# DIAGNOSTIC TOOL: PLOT TRAVERSAL & MIRRORING DETECTION
# ============================================================================
library(tidyverse)
library(fs)

# ============================================================================
# 1. USER CONFIGURATION
# ============================================================================
# Point this at the "Wide" output file generated by your main pipeline
WIDE_DATA_CSV <- "C:/Users/james.baker/Forest Research/TW CBC-TBA-NextGenBritishConifers - Share/Sitka/High GCA Fullsib P85-P87 experiments/Ae 58/Ae_58_Full_Data_With_Flags.csv"

PLOT_SIZE      <- 49       # Options: 8 (for 8x1 arrays) or 49 (for 7x7 grids), etc.
BASELINE_TRAIT <- "Ht_06"  # The trait you trust (Canonical order)
BASELINE_SURV  <- "Sur_06" # The survival record for the trusted trait
TEST_TRAIT     <- "Dm_15"  # The trait you suspect was traversed incorrectly
TEST_SURV      <- "Sur_15" # The survival record for the suspected trait

OUTPUT_DIR     <- dirname(WIDE_DATA_CSV) # Saves in the same folder as the input file

# ============================================================================
# 2. VIRTUAL ASSESSOR MATH ENGINE
# ============================================================================
get_grid_layout <- function(plot_size, interior_only = FALSE) {
  if (plot_size == 8) return(matrix(1:8, nrow=1))
  n <- as.integer(sqrt(plot_size))
  mat <- matrix(1:(n*n), nrow=n, byrow=TRUE)
  if(interior_only && n >= 3) mat <- mat[2:(n-1), 2:(n-1)]
  return(mat)
}

get_traversal_path <- function(layout_mat, start_corner="top_left", direction="horizontal", snake=FALSE) {
  if (length(layout_mat) == 8) {
    if (start_corner %in% c("reversed", "bottom_right")) return(rev(as.vector(layout_mat)))
    return(as.vector(layout_mat))
  }
  n_rows <- nrow(layout_mat)
  n_cols <- ncol(layout_mat)
  row_indices <- if (start_corner %in% c("bottom_left", "bottom_right")) rev(seq_len(n_rows)) else seq_len(n_rows)
  col_indices <- if (start_corner %in% c("top_right", "bottom_right")) rev(seq_len(n_cols)) else seq_len(n_cols)
  
  path <- c()
  if (direction == "horizontal") {
    for (i_idx in seq_along(row_indices)) {
      i <- row_indices[i_idx]
      cols <- col_indices
      if (snake && i_idx %% 2 == 0) cols <- rev(cols)
      for (j in cols) path <- c(path, layout_mat[i, j])
    }
  } else {
    for (j_idx in seq_along(col_indices)) {
      j <- col_indices[j_idx]
      rows <- row_indices
      if (snake && j_idx %% 2 == 0) rows <- rev(rows)
      for (i in rows) path <- c(path, layout_mat[i, j])
    }
  }
  return(path)
}

# ============================================================================
# 3. DATA LOADING & INTERIOR AUTODETECT
# ============================================================================
message(paste("Loading data from:", basename(WIDE_DATA_CSV)))
df <- read_csv(WIDE_DATA_CSV, show_col_types = FALSE)

working_data <- df %>%
  select(Plot, Tree, 
         Base_Val = !!sym(BASELINE_TRAIT), Base_Surv = !!sym(BASELINE_SURV), 
         Test_Val = !!sym(TEST_TRAIT), Test_Surv = !!sym(TEST_SURV)) %>%
  filter(!str_detect(Plot, "(?i)Filler")) %>%
  mutate(
    Tree = as.numeric(Tree),
    Plot = as.character(Plot),
    # REPEATABLE ZERO FILTER: Treat '0' in measurement as NA (erroneous data)
    Base_Val = na_if(as.numeric(Base_Val), 0),
    Test_Val = na_if(as.numeric(Test_Val), 0)
  )

# Auto-detect if TEST trait is full grid or interior only
test_trees_used <- unique(working_data %>% filter(!is.na(Test_Val)) %>% pull(Tree))
layout_interior <- as.vector(get_grid_layout(PLOT_SIZE, interior_only = TRUE))

is_test_interior <- FALSE
if (PLOT_SIZE > 8 && length(test_trees_used) > 0 && all(test_trees_used %in% layout_interior)) {
  is_test_interior <- TRUE
  message(paste("Detected", TEST_TRAIT, "as an INTERIOR-ONLY measurement."))
}

# Generate the Canonical path (What the main pipeline assumed)
layout_mat <- get_grid_layout(PLOT_SIZE, interior_only = is_test_interior)
canonical_path <- get_traversal_path(layout_mat, "top_left", "horizontal", FALSE)

# ============================================================================
# 4. PERMUTATION GENERATOR & DIAGNOSTIC ENGINE
# ============================================================================
if (PLOT_SIZE == 8) {
  combos <- tibble(Perm_ID = 1:2, start_corner = c("normal", "reversed"), direction = "horizontal", snake = FALSE)
} else {
  combos <- expand_grid(start_corner = c("top_left", "bottom_left", "top_right", "bottom_right"), direction = c("horizontal", "vertical"), snake = c(FALSE, TRUE)) %>% mutate(Perm_ID = row_number())
}

plots <- unique(working_data$Plot)
results_list <- list()

message(paste("Testing", length(plots), "plots against", nrow(combos), "traversal permutations..."))

for (p in plots) {
  plot_data <- working_data %>% filter(Plot == p)
  if(sum(!is.na(plot_data$Base_Val)) < 3 || sum(!is.na(plot_data$Test_Val)) < 3) next
  
  for (i in 1:nrow(combos)) {
    sc <- combos$start_corner[i]
    dir <- combos$direction[i]
    snk <- combos$snake[i]
    
    # Generate the tested path
    tested_path <- get_traversal_path(layout_mat, sc, dir, snk)
    
    # Create the translation table (moving data from assumed canonical to tested path)
    translation_df <- tibble(Original_Tree = canonical_path, Mapped_Tree = tested_path)
    
    mapped_test <- plot_data %>% 
      select(Tree, Test_Val, Test_Surv) %>%
      inner_join(translation_df, by = c("Tree" = "Original_Tree"))
    
    joined <- plot_data %>% 
      select(Tree, Base_Val, Base_Surv) %>% 
      left_join(mapped_test, by = c("Tree" = "Mapped_Tree"))
    
    zombie_count <- sum(joined$Base_Surv == 0 & (!is.na(joined$Test_Val) | joined$Test_Surv == 1), na.rm = TRUE)
    is_valid <- (zombie_count == 0)
    
    cor_data <- joined %>% filter(!is.na(Base_Val) & !is.na(Test_Val))
    spearman_cor <- if(nrow(cor_data) >= 3) cor(cor_data$Base_Val, cor_data$Test_Val, method = "spearman") else NA_real_
    
    results_list[[length(results_list) + 1]] <- tibble(Plot = p, Perm_ID = combos$Perm_ID[i], start_corner = sc, direction = dir, snake = snk, Zombies_Created = zombie_count, Is_Biologically_Valid = is_valid, Sample_Size = nrow(cor_data), Spearman_Cor = spearman_cor)
  }
}
all_results <- bind_rows(results_list)

# ============================================================================
# 5. SYNTHESIS & RECOMMENDATION GENERATOR
# ============================================================================
message("Synthesizing recommendations...")

recommendations <- all_results %>%
  group_by(Plot) %>%
  mutate(
    Normal_Cor = Spearman_Cor[start_corner %in% c("top_left", "normal") & direction == "horizontal" & snake == FALSE],
    Normal_Valid = Is_Biologically_Valid[start_corner %in% c("top_left", "normal") & direction == "horizontal" & snake == FALSE]
  ) %>%
  filter(Is_Biologically_Valid == TRUE) %>%
  arrange(desc(Spearman_Cor)) %>%
  slice(1) %>%
  ungroup() %>%
  mutate(
    Action_Required = case_when(
      start_corner %in% c("top_left", "normal") & direction == "horizontal" & snake == FALSE ~ "None (Normal is Best)",
      Normal_Valid == FALSE ~ "CRITICAL FIX: Normal layout creates Zombies",
      (Spearman_Cor - Normal_Cor) > 0.15 ~ "SUGGESTED FIX: Massive correlation improvement",
      TRUE ~ "Review Manually (Marginal Improvement)"
    )
  ) %>%
  select(Plot, Action_Required, Best_Start = start_corner, Best_Dir = direction, Best_Snake = snake, Best_Cor = Spearman_Cor, Normal_Cor, Sample_Size) %>%
  arrange(desc(Action_Required))

write_csv(all_results, file.path(OUTPUT_DIR, paste0(BASELINE_TRAIT, "_vs_", TEST_TRAIT, "_All_Permutations.csv")))
write_csv(recommendations, file.path(OUTPUT_DIR, paste0("Suggested_Fixes_", TEST_TRAIT, ".csv")))

# Calculate dominant behavior
dominant_fix <- recommendations %>% filter(Action_Required == "FIX REQUIRED") %>%
  count(start_corner, direction, snake) %>% arrange(desc(n)) %>% slice(1)

# Console Output: The Forensic Report
cat("\n========================================================\n")
cat("FORENSIC ASSESSOR REPORT for:", TEST_TRAIT, "vs", BASELINE_TRAIT, "\n")
cat("========================================================\n")
cat("1. ASSUMED PROTOCOL (Baseline): Top-Left, Horizontal, Typewriter\n")

if (nrow(dominant_fix) > 0) {
  cat(sprintf("2. DETECTED BEHAVIOR: Majority of errored plots followed: %s, %s (Snake: %s)\n", 
              toupper(dominant_fix$start_corner), toupper(dominant_fix$direction), dominant_fix$snake))
  
  # Identify plots that deviate from the dominant error
  rebels <- recommendations %>% 
    filter(Action_Required == "FIX REQUIRED") %>%
    filter(start_corner != dominant_fix$start_corner | direction != dominant_fix$direction | snake != dominant_fix$snake)
  
  if (nrow(rebels) > 0) {
    cat("3. PATTERN SHIFTS: The following plots deviated from the primary error pattern:\n")
    for(r in 1:nrow(rebels)) {
      cat(sprintf("   - Plot %s: Used %s, %s (Snake: %s)\n", 
                  rebels$Plot[r], rebels$start_corner[r], rebels$direction[r], rebels$snake[r]))
    }
  } else {
    cat("3. PATTERN CONSISTENCY: Assessor was highly consistent in their specific error.\n")
  }
} else {
  cat("2. DETECTED BEHAVIOR: No systematic traversal errors detected.\n")
}
cat("========================================================\n\n")

# ============================================================================
# 6. VISUALIZATION: BEFORE VS AFTER VS GLOBAL RULE
# ============================================================================
message("Generating visualization panels...")

before_df <- working_data %>% select(Plot, Tree, Base_Val, Test_Val) %>% mutate(State = "1. Original Raw Data")

after_list <- list()
for (p in unique(working_data$Plot)) {
  p_data <- working_data %>% filter(Plot == p)
  rec <- recommendations %>% filter(Plot == p)
  
  if (nrow(rec) == 1 && !str_detect(rec$Action_Required, "(?i)None")) {
    tested_path <- get_traversal_path(layout_mat, rec$Best_Start, rec$Best_Dir, rec$Best_Snake)
    translation_df <- tibble(Original_Tree = canonical_path, Mapped_Tree = tested_path)
    
    fixed_test <- p_data %>% select(Tree, Test_Val) %>% inner_join(translation_df, by = c("Tree" = "Original_Tree"))
    
    p_joined <- p_data %>% select(Plot, Tree, Base_Val) %>% left_join(fixed_test, by = c("Tree" = "Mapped_Tree"))
    after_list[[length(after_list) + 1]] <- p_joined
  } else {
    after_list[[length(after_list) + 1]] <- p_data %>% select(Plot, Tree, Base_Val, Test_Val)
  }
}
after_df <- bind_rows(after_list) %>% mutate(State = "2. Targeted Fixes (Inc. Marginal)")

global_sc <- if(PLOT_SIZE == 8) "reversed" else "bottom_right"
global_path <- get_traversal_path(layout_mat, global_sc, "horizontal", FALSE)
global_translation <- tibble(Original_Tree = canonical_path, Mapped_Tree = global_path)

global_test <- working_data %>% select(Plot, Tree, Test_Val) %>% inner_join(global_translation, by = c("Tree" = "Original_Tree"))
global_df <- working_data %>% select(Plot, Tree, Base_Val) %>% left_join(global_test, by = c("Plot", "Tree" = "Mapped_Tree")) %>% mutate(State = "3. Global Rule Fix")

plot_df <- bind_rows(before_df, after_df, global_df) %>% filter(!is.na(Base_Val) & !is.na(Test_Val))

calc_cor <- function(df) round(cor(df$Base_Val, df$Test_Val, use = "pairwise.complete.obs", method = "spearman"), 3)
cor_before <- calc_cor(before_df)
cor_after  <- calc_cor(after_df)
cor_global <- calc_cor(global_df)

p_compare <- ggplot(plot_df, aes(x = Base_Val, y = Test_Val)) +
  geom_point(alpha = 0.5, color = "#2c3e50") +
  geom_smooth(method = "lm", color = "#e74c3c", linetype = "dashed", se = FALSE) +
  facet_wrap(~State, ncol = 3) +
  theme_bw() +
  labs(
    title = paste("Plot Traversal Correction:", BASELINE_TRAIT, "vs", TEST_TRAIT),
    subtitle = sprintf("Trial Correlations  ->  Raw: %s  |  Targeted Fix: %s  |  Global Fix: %s", cor_before, cor_after, cor_global),
    x = paste("Trusted Baseline:", BASELINE_TRAIT),
    y = paste("Suspected Trait:", TEST_TRAIT)
  ) +
  theme(strip.background = element_rect(fill = "#ecf0f1"), strip.text = element_text(face = "bold", size = 11), plot.title = element_text(face = "bold", size = 14))

plot_path <- file.path(OUTPUT_DIR, paste0(BASELINE_TRAIT, "_vs_", TEST_TRAIT, "_Correction_Plot.png"))
ggsave(plot_path, p_compare, width = 12, height = 5)

message(paste("Results and Plot saved to:", OUTPUT_DIR))